# Generated by Django 2.1.4 on 2019-02-17 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmountGrowthTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField()),
                ('amount_total', models.FloatField()),
            ],
            options={
                'db_table': 'amount_growth_total',
            },
        ),
        migrations.CreateModel(
            name='Fans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fans_id', models.IntegerField()),
                ('fans_name', models.CharField(max_length=100)),
                ('account', models.FloatField()),
            ],
            options={
                'db_table': 'fans',
            },
        ),
        migrations.CreateModel(
            name='FansClub',
            fields=[
                ('fans_club', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('is_cp_club', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fans_club',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('join_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('goal_amount', models.FloatField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('fans_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FansClub')),
            ],
            options={
                'db_table': 'project_info',
            },
        ),
        migrations.CreateModel(
            name='ProjectSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField(auto_now=True)),
                ('real_amount', models.FloatField()),
                ('support_no', models.IntegerField(null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.ProjectInfo')),
            ],
            options={
                'db_table': 'project_sample',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('theater', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'theater',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Theater'),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Team'),
        ),
        migrations.AddField(
            model_name='member',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Theater'),
        ),
        migrations.AddField(
            model_name='fansclub',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Member'),
        ),
        migrations.AddField(
            model_name='fans',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.ProjectInfo'),
        ),
    ]
