# Generated by Django 2.1.4 on 2019-02-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountGrowthTheater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_time', models.DateTimeField()),
                ('theater', models.CharField(max_length=50)),
                ('amount_theater', models.FloatField()),
            ],
            options={
                'db_table': 'amount_growth_theater',
            },
        ),
        migrations.CreateModel(
            name='G101GrowthTotal',
            fields=[
                ('sample_time', models.DateTimeField(primary_key=True, serialize=False)),
                ('amount_total', models.FloatField()),
            ],
            options={
                'db_table': 'g101_growth_total',
            },
        ),
        migrations.CreateModel(
            name='G102GrowthTheater',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sample_time', models.DateTimeField()),
                ('theater', models.CharField(max_length=50)),
                ('amount_theater', models.FloatField()),
            ],
            options={
                'db_table': 'g102_growth_theater',
            },
        ),
        migrations.CreateModel(
            name='V103RealTimeAmount',
            fields=[
                ('member', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('real_amount', models.FloatField()),
                ('support_no', models.IntegerField()),
            ],
            options={
                'db_table': 'v103_real_time_amount',
                'ordering': ['-real_amount'],
            },
        ),
        migrations.RemoveField(
            model_name='amountgrowthtotal',
            name='id',
        ),
        migrations.AlterField(
            model_name='amountgrowthtotal',
            name='sample_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
