
# Member list.
member_sii = ["陈观慧", "陈俊羽", "陈思", "戴萌", "蒋芸", "孔肖吟", "李宇琪", "刘增艳", "莫寒", "钱蓓婷",
              "邱欣怡", "孙芮", "邵雪聪", "温晶婕", "吴哲晗", "徐晨辰", "许佳琪", "徐子轩", "袁丹妮",
              "杨令仪", "袁雨桢", "朱小丹", "张语格"]
member_nii = ["陈佳莹", "冯薪朵", "黄婷婷", "何晓玉", "金莹玥", "江真仪", "刘洁", "栾嘉仪", "李美琪",
              "陆婷", "卢天惠", "马凡", "王诗蒙", "谢妮", "易嘉爱", "颜沁", "赵佳蕊", "周诗雨", "张茜",
              "赵粤", "张怡", "张雨鑫"]
member_hii = ["陈盼", "费沁源", "郭爽", "郝婧怡", "洪珮雲", "姜杉", "蒋舒婷", "林楠", "林舒晴", "林思意",
              "李玉倩", "李艺彤", "戚予珠", "沈梦瑶", "宋雨珊", "孙珍妮", "万丽娜", "王欣颜甜甜", "王奕",
              "徐晗", "许杨玉琢", "袁一琦", "张昕"]
member_x = ["陈琳", "冯晓菲", "刘静晗", "鲁静萍", "李星羽", "吕一", "李钊", "潘瑛琪", "祁静", "冉蔚",
            "宋昕冉", " 孙歆文", "王菲妍", "汪佳翎", "王晓佳", "谢天依", "杨冰怡", "张丹三", "张嘉予"]
member_b = ["程戈", "陈美君", "段艺璇", "胡丽芝", "胡晓慧", "刘姝贤", "林溪荷", "李瑜璇", "曲美霖",
            "青钰雯", "沈小爱", "孙晓艳", "田姝丽", "熊素君", "闫明筠", "杨鑫", "张梦慧", "赵天杨", "张羽涵"]
member_e = ["陈倩楠", "程宇璐", "冯思佳", "高蔚然", "李丽满", "李娜", "刘胜男", "李诗彦", "李梓", "马玉灵",
            "彭嘉敏", "任蔓琳", "苏杉杉", "王嘉瑜", "王雨兰", "顼凘炀", "熊鑫", "杨一帆", "张爱静", "臧聪",
            "张丹丹", "张笑盈"]
member_j = ["柏欣妤", "陈雅钰", "房蕾", "葛司琪", "黄恩茹", "韩家乐", "何阳青青", "金锣赛", "楼澍", "刘闲",
            "刘一菲", "任心怡", "孙语姗", "唐霖", "王雨煊", "叶苗苗", "杨晔", "张怀瑾", "郑洁丽", "周湘"]
member_g = ["陈俊宏", "GNZ48陈佳莹", "陈珂", "符冰冰", "高源婧", "黄楚茵", "罗寒月", "梁娇", "林嘉佩",
            "罗可嘉", "李沁洁", "李姗姗", "林芝", "徐楚雯", "徐慧玲", "谢蕾蕾", "阳青颖", "叶舒淇",
            "曾艾佳", "张琼予", "朱怡欣"]
member_niii = ["陈楠茜", "陈欣妤", "邓熳慧", "高雪逸", "洪静雯", "卢静", "刘力菲", "刘倩倩", "孙馨",
               "唐莉佳", "吴羽霏", "谢艾琳", "冼燊楠", "肖文铃", "熊心瑶", "郑丹妮", "左嘉欣", "左婧媛",
               "张润"]
member_z = ["毕瑞珊", "陈桂君", "邓惠恩", "杜秋霖", "方琪", "郭铱宁", "何梦瑶", "梁乔", "梁婉琳", "龙亦瑞",
            "赖梓惜", "农燕萍", "王翠菲", "王炯义", "王偲越", "谢菲菲", "杨可璐", "杨媛媛", "余芷媛",
            "张秋怡"]

# Member avatar
member_avatar = {
    # Team SII
    "陈观慧": "http://www.snh48.com/images/member/zp_10001.jpg",
    "陈俊羽": "http://www.snh48.com/images/member/zp_10206.jpg",
    "陈思": "http://www.snh48.com/images/member/zp_10002.jpg",
    "戴萌": "http://www.snh48.com/images/member/zp_10003.jpg",
    "蒋芸": "http://www.snh48.com/images/member/zp_10004.jpg",
    "孔肖吟": "http://www.snh48.com/images/member/zp_10005.jpg",
    "李宇琪": "http://www.snh48.com/images/member/zp_10006.jpg",
    "刘增艳": "http://www.snh48.com/images/member/zp_10125.jpg",
    "莫寒": "http://www.snh48.com/images/member/zp_10007.jpg",
    "钱蓓婷": "http://www.snh48.com/images/member/zp_10008.jpg",
    "邱欣怡": "http://www.snh48.com/images/member/zp_10009.jpg",
    "孙芮": "http://www.snh48.com/images/member/zp_10010.jpg",
    "邵雪聪": "http://www.snh48.com/images/member/zp_10086.jpg",
    "温晶婕": "http://www.snh48.com/images/member/zp_10012.jpg",
    "吴哲晗": "http://www.snh48.com/images/member/zp_10013.jpg",
    "徐晨辰": "http://www.snh48.com/images/member/zp_10014.jpg",
    "许佳琪": "http://www.snh48.com/images/member/zp_10015.jpg",
    "徐子轩": "http://www.snh48.com/images/member/zp_10016.jpg",
    "袁丹妮": "http://www.snh48.com/images/member/zp_10073.jpg",
    "杨令仪": "http://www.snh48.com/images/member/zp_10193.jpg",
    "袁雨桢": "http://www.snh48.com/images/member/zp_10017.jpg",
    "朱小丹": "http://www.snh48.com/images/member/zp_10197.jpg",
    "张语格": "http://www.snh48.com/images/member/zp_10019.jpg",

    # Team NII
    "陈佳莹": "http://www.snh48.com/images/member/zp_10020.jpg",
    "冯薪朵": "http://www.snh48.com/images/member/zp_10023.jpg",
    "黄婷婷": "http://www.snh48.com/images/member/zp_10025.jpg",
    "何晓玉": "http://www.snh48.com/images/member/zp_10026.jpg",
    "金莹玥": "http://www.snh48.com/images/member/zp_10178.jpg",
    "江真仪": "http://www.snh48.com/images/member/zp_10156.jpg",
    "刘洁": "http://www.snh48.com/images/member/zp_10201.jpg",
    "栾嘉仪": "http://www.snh48.com/images/member/zp_10202.jpg",
    "李美琪": "http://www.snh48.com/images/member/zp_10187.jpg",
    "陆婷": "http://www.snh48.com/images/member/zp_10030.jpg",
    "卢天惠": "http://www.snh48.com/images/member/zp_10207.jpg",
    "马凡": "http://www.snh48.com/images/member/zp_10185.jpg",
    "王诗蒙": "http://www.snh48.com/images/member/zp_10208.jpg",
    "谢妮": "http://www.snh48.com/images/member/zp_10067.jpg",
    "易嘉爱": "http://www.snh48.com/images/member/zp_10036.jpg",
    "颜沁": "http://www.snh48.com/images/member/zp_10205.jpg",
    "赵佳蕊": "http://www.snh48.com/images/member/zp_10209.jpg",
    "周诗雨": "http://www.snh48.com/images/member/zp_10196.jpg",
    "张茜": "http://www.snh48.com/images/member/zp_10195.jpg",
    "赵粤": "http://www.snh48.com/images/member/zp_10037.jpg",
    "张怡": "http://www.snh48.com/images/member/zp_10141.jpg",
    "张雨鑫": "http://www.snh48.com/images/member/zp_10076.jpg",

    # Team HII
    "陈盼": "http://www.snh48.com/images/member/zp_10186.jpg",
    "费沁源": "http://www.snh48.com/images/member/zp_10114.jpg",
    "郭爽": "http://www.snh48.com/images/member/zp_10210.jpg",
    "郝婧怡": "http://www.snh48.com/images/member/zp_10211.jpg",
    "洪珮雲": "http://www.snh48.com/images/member/zp_10117.jpg",
    "姜杉": "http://www.snh48.com/images/member/zp_10119.jpg",
    "蒋舒婷": "http://www.snh48.com/images/member/zp_10120.jpg",
    "林楠": "http://www.snh48.com/images/member/zp_10061.jpg",
    "林舒晴": "http://www.snh48.com/images/member/zp_10212.jpg",
    "林思意": "http://www.snh48.com/images/member/zp_10029.jpg",
    "李玉倩": "http://www.snh48.com/images/member/zp_10189.jpg",
    "李艺彤": "http://www.snh48.com/images/member/zp_10031.jpg",
    "戚予珠": "http://www.snh48.com/images/member/zp_10199.jpg",
    "沈梦瑶": "http://www.snh48.com/images/member/zp_10104.jpg",
    "宋雨珊": "http://www.snh48.com/images/member/zp_10129.jpg",
    "孙珍妮": "http://www.snh48.com/images/member/zp_10146.jpg",
    "万丽娜": "http://www.snh48.com/images/member/zp_10034.jpg",
    "王欣颜甜甜": "http://www.snh48.com/images/member/zp_10192.jpg",
    "王奕": "http://www.snh48.com/images/member/zp_10181.jpg",
    "徐晗": "http://www.snh48.com/images/member/zp_10068.jpg",
    "许杨玉琢": "http://www.snh48.com/images/member/zp_10070.jpg",
    "袁一琦": "http://www.snh48.com/images/member/zp_10163.jpg",
    "张昕": "http://www.snh48.com/images/member/zp_10075.jpg",

    # Team X
    "陈琳": "http://www.snh48.com/images/member/zp_10081.jpg",
    "冯晓菲": "http://www.snh48.com/images/member/zp_10082.jpg",
    "刘静晗": "http://www.snh48.com/images/member/zp_10213.jpg",
    "鲁静萍": "http://www.snh48.com/images/member/zp_10204.jpg",
    "李星羽": "http://www.snh48.com/images/member/zp_10188.jpg",
    "吕一": "http://www.snh48.com/images/member/zp_10153.jpg",
    "李钊": "http://www.snh48.com/images/member/zp_10084.jpg",
    "潘瑛琪": "http://www.snh48.com/images/member/zp_10126.jpg",
    "祁静": "http://www.snh48.com/images/member/zp_10164.jpg",
    "冉蔚": "http://www.snh48.com/images/member/zp_10214.jpg",
    "宋昕冉": "http://www.snh48.com/images/member/zp_10087.jpg",
    "孙歆文": "http://www.snh48.com/images/member/zp_10088.jpg",
    "王菲妍": "http://www.snh48.com/images/member/zp_10215.jpg",
    "汪佳翎": "http://www.snh48.com/images/member/zp_10089.jpg",
    "王晓佳": "http://www.snh48.com/images/member/zp_10091.jpg",
    "谢天依": "http://www.snh48.com/images/member/zp_10092.jpg",
    "杨冰怡": "http://www.snh48.com/images/member/zp_10093.jpg",
    "张丹三": "http://www.snh48.com/images/member/zp_10096.jpg",
    "张嘉予": "http://www.snh48.com/images/member/zp_10149.jpg",

    # Team B
    "程戈": "http://www.bej48.com/images/member/zp_20100.jpg",
    "陈美君": "http://www.bej48.com/images/member/zp_20001.jpg",
    "段艺璇": "http://www.bej48.com/images/member/zp_20003.jpg",
    "胡丽芝": "http://www.bej48.com/images/member/zp_20058.jpg",
    "胡晓慧": "http://www.bej48.com/images/member/zp_20006.jpg",
    "刘姝贤": "http://www.bej48.com/images/member/zp_20007.jpg",
    "林溪荷": "http://www.bej48.com/images/member/zp_20008.jpg",
    "李瑜璇": "http://www.bej48.com/images/member/zp_20110.jpg",
    "曲美霖": "http://www.bej48.com/images/member/zp_20088.jpg",
    "青钰雯": "http://www.bej48.com/images/member/zp_20010.jpg",
    "沈小爱": "http://www.bej48.com/images/member/zp_20073.jpg",
    "孙晓艳": "http://www.bej48.com/images/member/zp_20062.jpg",
    "田姝丽": "http://www.bej48.com/images/member/zp_20013.jpg",
    "熊素君": "http://www.bej48.com/images/member/zp_20017.jpg",
    "闫明筠": "http://www.bej48.com/images/member/zp_20019.jpg",
    "杨鑫": "http://www.bej48.com/images/member/zp_20081.jpg",
    "张梦慧": "http://www.bej48.com/images/member/zp_20021.jpg",
    "赵天杨": "http://www.bej48.com/images/member/zp_20101.jpg",
    "张羽涵": "http://www.bej48.com/images/member/zp_20102.jpg",

    # Team E
    "陈倩楠": "http://www.bej48.com/images/member/zp_20024.jpg",
    "程宇璐": "http://www.bej48.com/images/member/zp_20093.jpg",
    "冯思佳": "http://www.bej48.com/images/member/zp_20025.jpg",
    "高蔚然": "http://www.bej48.com/images/member/zp_20084.jpg",
    "李丽满": "http://www.bej48.com/images/member/zp_20094.jpg",
    "李娜": "http://www.bej48.com/images/member/zp_20078.jpg",
    "刘胜男": "http://www.bej48.com/images/member/zp_20028.jpg",
    "李诗彦": "http://www.bej48.com/images/member/zp_20029.jpg",
    "李梓": "http://www.bej48.com/images/member/zp_20033.jpg",
    "马玉灵": "http://www.bej48.com/images/member/zp_20034.jpg",
    "彭嘉敏": "http://www.bej48.com/images/member/zp_20087.jpg",
    "任蔓琳": "http://www.bej48.com/images/member/zp_20095.jpg",
    "苏杉杉": "http://www.bej48.com/images/member/zp_20035.jpg",
    "王嘉瑜": "http://www.bej48.com/images/member/zp_20103.jpg",
    "王雨兰": "http://www.bej48.com/images/member/zp_20104.jpg",
    "顼凘炀": "http://www.bej48.com/images/member/zp_20036.jpg",
    "熊鑫": "http://www.bej48.com/images/member/zp_20089.jpg",
    "杨一帆": "http://www.bej48.com/images/member/zp_20037.jpg",
    "张爱静": "http://www.bej48.com/images/member/zp_20105.jpg",
    "臧聪": "http://www.bej48.com/images/member/zp_20106.jpg",
    "张丹丹": "http://www.bej48.com/images/member/zp_20091.jpg",
    "张笑盈": "http://www.bej48.com/images/member/zp_20039.jpg",

    # Team J
    "柏欣妤": "http://www.bej48.com/images/member/zp_20099.jpg",
    "陈雅钰": "http://www.bej48.com/images/member/zp_20041.jpg",
    "房蕾": "http://www.bej48.com/images/member/zp_20042.jpg",
    "葛司琪": "http://www.bej48.com/images/member/zp_20043.jpg",
    "黄恩茹": "http://www.bej48.com/images/member/zp_20044.jpg",
    "韩家乐": "http://www.bej48.com/images/member/zp_20107.jpg",
    "何阳青青": "http://www.bej48.com/images/member/zp_20080.jpg",
    "金锣赛": "http://www.bej48.com/images/member/zp_20068.jpg",
    "楼澍": "http://www.bej48.com/images/member/zp_20086.jpg",
    "刘闲": "http://www.bej48.com/images/member/zp_20046.jpg",
    "刘一菲": "http://www.bej48.com/images/member/zp_20070.jpg",
    "任心怡": "http://www.bej48.com/images/member/zp_20047.jpg",
    "孙语姗": "http://www.bej48.com/images/member/zp_20051.jpg",
    "唐霖": "http://www.bej48.com/images/member/zp_20108.jpg",
    "王雨煊": "http://www.bej48.com/images/member/zp_20052.jpg",
    "叶苗苗": "http://www.bej48.com/images/member/zp_20054.jpg",
    "杨晔": "http://www.bej48.com/images/member/zp_20055.jpg",
    "张怀瑾": "http://www.bej48.com/images/member/zp_20056.jpg",
    "郑洁丽": "http://www.bej48.com/images/member/zp_20109.jpg",
    "周湘": "http://www.bej48.com/images/member/zp_20092.jpg",

    # Team G
    "陈俊宏": "http://www.gnz48.com/images/member/zp_30058.jpg",
    "GNZ48陈佳莹": "http://www.gnz48.com/images/member/zp_30057.jpg",
    "陈珂": "http://www.gnz48.com/images/member/zp_30001.jpg",
    "符冰冰": "http://www.gnz48.com/images/member/zp_30075.jpg",
    "高源婧": "http://www.gnz48.com/images/member/zp_30004.jpg",
    "黄楚茵": "http://www.gnz48.com/images/member/zp_30076.jpg",
    "罗寒月": "http://www.gnz48.com/images/member/zp_30010.jpg",
    "梁娇": "http://www.gnz48.com/images/member/zp_30092.jpg",
    "林嘉佩": "http://www.gnz48.com/images/member/zp_30007.jpg",
    "罗可嘉": "http://www.gnz48.com/images/member/zp_30078.jpg",
    "李沁洁": "http://www.gnz48.com/images/member/zp_30006.jpg",
    "李姗姗": "http://www.gnz48.com/images/member/zp_30101.jpg",
    "林芝": "http://www.gnz48.com/images/member/zp_30080.jpg",
    "徐楚雯": "http://www.gnz48.com/images/member/zp_30102.jpg",
    "徐慧玲": "http://www.gnz48.com/images/member/zp_30103.jpg",
    "谢蕾蕾": "http://www.gnz48.com/images/member/zp_30012.jpg",
    "阳青颖": "http://www.gnz48.com/images/member/zp_30013.jpg",
    "叶舒淇": "http://www.gnz48.com/images/member/zp_30098.jpg",
    "曾艾佳": "http://www.gnz48.com/images/member/zp_30014.jpg",
    "张琼予": "http://www.gnz48.com/images/member/zp_30016.jpg",
    "朱怡欣": "http://www.gnz48.com/images/member/zp_30071.jpg",

    # Team NIII
    "陈楠茜": "http://www.gnz48.com/images/member/zp_30020.jpg",
    "陈欣妤": "http://www.gnz48.com/images/member/zp_30021.jpg",
    "邓熳慧": "http://www.gnz48.com/images/member/zp_30097.jpg",
    "高雪逸": "http://www.gnz48.com/images/member/zp_30062.jpg",
    "洪静雯": "http://www.gnz48.com/images/member/zp_30023.jpg",
    "卢静": "http://www.gnz48.com/images/member/zp_30026.jpg",
    "刘力菲": "http://www.gnz48.com/images/member/zp_30024.jpg",
    "刘倩倩": "http://www.gnz48.com/images/member/zp_30025.jpg",
    "孙馨": "http://www.gnz48.com/images/member/zp_30027.jpg",
    "唐莉佳": "http://www.gnz48.com/images/member/zp_30028.jpg",
    "吴羽霏": "http://www.gnz48.com/images/member/zp_30082.jpg",
    "谢艾琳": "http://www.gnz48.com/images/member/zp_30068.jpg",
    "冼燊楠": "http://www.gnz48.com/images/member/zp_30029.jpg",
    "肖文铃": "http://www.gnz48.com/images/member/zp_30030.jpg",
    "熊心瑶": "http://www.gnz48.com/images/member/zp_30031.jpg",
    "郑丹妮": "http://www.gnz48.com/images/member/zp_30032.jpg",
    "左嘉欣": "http://www.gnz48.com/images/member/zp_30033.jpg",
    "左婧媛": "http://www.gnz48.com/images/member/zp_30034.jpg",
    "张润": "http://www.gnz48.com/images/member/zp_30100.jpg",

    # Team Z
    "毕瑞珊": "http://www.gnz48.com/images/member/zp_30072.jpg",
    "陈桂君": "http://www.gnz48.com/images/member/zp_30048.jpg",
    "邓惠恩": "http://www.gnz48.com/images/member/zp_30074.jpg",
    "杜秋霖": "http://www.gnz48.com/images/member/zp_30040.jpg",
    "方琪": "http://www.gnz48.com/images/member/zp_30104.jpg",
    "郭铱宁": "http://www.gnz48.com/images/member/zp_30091.jpg",
    "何梦瑶": "http://www.gnz48.com/images/member/zp_30077.jpg",
    "梁乔": "http://www.gnz48.com/images/member/zp_30093.jpg",
    "梁婉琳": "http://www.gnz48.com/images/member/zp_30079.jpg",
    "龙亦瑞": "http://www.gnz48.com/images/member/zp_30054.jpg",
    "赖梓惜": "http://www.gnz48.com/images/member/zp_30105.jpg",
    "农燕萍": "http://www.gnz48.com/images/member/zp_30043.jpg",
    "王翠菲": "http://www.gnz48.com/images/member/zp_30050.jpg",
    "王炯义": "http://www.gnz48.com/images/member/zp_30055.jpg",
    "王偲越": "http://www.gnz48.com/images/member/zp_30042.jpg",
    "王秭歆": "http://www.gnz48.com/images/member/zp_30041.jpg",
    "谢菲菲": "http://www.gnz48.com/images/member/zp_30095.jpg",
    "杨可璐": "http://www.gnz48.com/images/member/zp_30047.jpg",
    "杨媛媛": "http://www.gnz48.com/images/member/zp_30046.jpg",
    "余芷媛": "http://www.gnz48.com/images/member/zp_30084.jpg",
    "张秋怡": "http://www.gnz48.com/images/member/zp_30069.jpg",
}
